### ISSUE TITLE
Error in ApolloExample.vue component

### ISSUE THREAD

**Issue by volny** [Akryum/vue-cli-plugin-apollo#69]
I'm getting an error using the provided `ApolloExample.vue` component right after install in a brand-new vue app. The API url seems to be wrong, this is what I get in my browser console

```
Hello%20World:1 GET http://localhost:4000/Hello%20World 404 (Not Found)
```

Steps to reproduce:
- `vue create project`
- `vue add apollo`
- `yarn run apollo`
- `yarn run serve`
- render the `ApolloExample` component in the app

Am I missing something obvious here?

**Comment by NataliaTepluhina** [comment]
@volny  As a quick fix, try to disable automatic resolvers mocking when creating a project or set `enableMocks` property to `false` in `vue.config.js`.

There is an issue that despite the prompt message says _Missing resolvers will be automatically mocked_ right now all resolvers are mocked (even if you specify some). That's why you get `Hello World` string as an image name (and 404 error).
